name: Genicons Workflow

on: [push]

jobs:
  pre-commit:
    # Git-secret

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL DB
        run: |
          docker build -t db_image tmp/sql/
          docker run -d --name test_db -p 3306:3306 db_image
      - name: Set up Python3.8
        run: |
          python -m pip install --upgrade pip
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 $HOME/genicons/api/app --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest pytest-env jsonschema
          cd $HOME/genicons/api/app/test && pytest
      - name: SCA & SAST with synopsys
      - name: DAST with owasp zap

  deploy:
    runs-on: ubuntu-latest
    if: job.status == "success"
    steps:
