repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: '^fastapi/.*/\.py'
        exclude: ^(fastapi/app/alembic/|fastapi/app/test/schema/)
        args: ["--count", "--statistics", "--max-line-length", "88"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: '^fastapi/.*/\.py'
        exclude: ^(fastapi/app/alembic/|fastapi/app/test/schema/)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.20.0
    hooks:
      - id: eslint
        types: [file]
        types_or: [ts]  # [ts, vue]
        additional_dependencies:
          - eslint@7.29.0
          - eslint-plugin-nuxt@2.0.0
          - eslint-plugin-vue@7.12.1
