repos:
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(nuxt/|tmp/|sql/|scripts/|doc/|fastapi/app/alembic/|fastapi/app/test/schema/)
        args: ["--count", "--statistics", "--max-line-length", "88"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^(nuxt/|tmp/|sql/|scripts/|doc/)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: ['--exclude-lines', 'D:MYSQL_PASSWORD=.*$', '--exclude-lines', '^(down_)?revision.*$']
