version: '3.9'

services:
  db:
    container_name: "db"
    build: ./sql
    restart: always
    tty: true
    env_file:
      - ./sql/.env
    ports:
      - "3306:3306"
    networks:
      - genicons-api-net

  fastapi:
    links:
      - db
    container_name: "fastapi"
    build: ./fastapi
    restart: always
    tty: true
    env_file:
      - ./fastapi/.env
    ports:
      - "8888:8888"
    networks:
      - genicons-api-net

networks:
  genicons-api-net:
    driver: bridge
