version: '3.9'

services:
  db:
    container_name: "db"
    build: ./sql
    restart: always
    tty: true
    env_file:
      - ./sql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./sql/conf.d:/etc/mysql/conf.d
    networks:
      - genicons-api-net

  api:
    links:
      - db
    container_name: "api"
    build: ./api
    restart: always
    tty: true
    env_file:
      - ./api/.env
    ports:
      - "8888:8888"
    volumes:
      - ./api/app:/app
    networks:
      - genicons-api-net

networks:
  genicons-api-net:
    driver: bridge
