FROM python:3.8

RUN apt-get update && apt-get install -y \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY ./* /usr/src/api/

WORKDIR /usr/src/api

# コンテナ起動後、FastAPIアプリの起動
CMD ["gunicorn", "-c", "./gunicorn.py", "main:app"]
