"""new tables

Revision ID: 0061ed22f5d6
Revises: 9e3c281849cc
Create Date: 2022-07-12 05:40:06.540548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "0061ed22f5d6"
down_revision = "9e3c281849cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "product_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("origin_img", sa.LargeBinary(length=16777216), nullable=False),
    )
    op.drop_column("products", "id")
    op.add_column("users", sa.Column("name", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("users", sa.Column("premium", sa.BOOLEAN(), nullable=True))
    op.drop_column("users", "img")
    op.drop_column("users", "img_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("img_name", mysql.VARCHAR(length=20), nullable=False)
    )
    op.add_column("users", sa.Column("img", mysql.LONGBLOB(), nullable=False))
    op.drop_column("users", "premium")
    op.drop_column("users", "email")
    op.drop_column("users", "name")
    op.add_column(
        "products", sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_column("products", "origin_img")
    op.drop_column("products", "product_id")
    # ### end Alembic commands ###
