"""empty message

Revision ID: 04b83e6636a9
Revises: f4a3acfa3464
Create Date: 2022-07-12 03:43:50.640636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04b83e6636a9"
down_revision = "f4a3acfa3464"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
