"""add password to users table

Revision ID: 678e35c47327
Revises: 3f536067e13d
Create Date: 2022-07-28 12:35:55.255966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "678e35c47327"
down_revision = "3f536067e13d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, "users", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
