"""create tables

Revision ID: 9e3c281849cc
Revises: 04b83e6636a9
Create Date: 2022-07-12 03:58:56.824345

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "9e3c281849cc"
down_revision = "04b83e6636a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("img", sa.LargeBinary(length=16777216), nullable=False),
        sa.Column("img_name", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "rounded_square_icon", sa.LargeBinary(length=16777216), nullable=True
        ),
        sa.Column("circle_icon", sa.LargeBinary(length=16777216), nullable=True),
        sa.Column(
            "users_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["users_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("users")
    # ### end Alembic commands ###
