version: "3.8"

services:
  # MySQL
  db:
    container_name: "db"
    build: ./mysql        # 指定したディレクトリ配下のDockerfileを読み込む
    restart: always       # 常にコンテナが落ちたら再起動させる
    tty: true             # コンテナを起動させ続けることができる
    environment:          # コンテナ内の環境変数の設定
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/etc/mysql/initdb.d  # 定義どおりにテーブル作成
      - ./mysql/conf.d:/etc/mysql/conf.d      # MySQLの基本設定（文字化け対策）
      - ./log/mysql:/var/log/mysql            # ログの保存
    networks:
      - genicons-api-net

  # FastAPI App
  api:
    links:                # dbコンテナを起動後に立ち上げる
      - db
    container_name: "api"
    build: ./api
    restart: always
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/api
    networks:
      - genicons-api-net

networks:
  genicons-api-net:
    driver: bridge
