name: Genicons CI prod

on:
  workflow_run:
    workflows: ["Genicons CI stage"]
    types:
      - completed

jobs:
  stage:
    runs-on: ubuntu-latest
          
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Migration to "Production" env
        run: |
          echo "Use Kubernetes?"
      - name: Monitoring, Guardrails
        run: |
          echo "??"
