name: Genicons CI stage

on:
  workflow_run:
    workflows: ["Genicons CI build"]
    types:
      - completed

jobs:
  stage:
    runs-on: ubuntu-latest
          
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      ## Migration to "Staging" env
      - name: Make Docker container
      ## DAST, Inflastructure scan
