name: Genicons CI stage

on:
  workflow_run:
    workflows: ["Genicons CI build"]
    types:
      - completed

jobs:
  stage:
    runs-on: ubuntu-latest
          
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Migration to Staging env
        run: |
          echo "Use Terraform?"
          echo "Use Ansible?"
      - name: DAST, Inflastructure scan
        run: |
          echo "NMAP to AWS staging env"
          echo "OWASP ZAP to AWS staging env"
